

package:
  name: "rest_regression"
  version: "2026.1.0.3"

source:
  - git: https://{{ env.get("GITEE_USER") }}:{{ env.get("GITEE_TOKEN") }}@gitee.com/restgroup/rest_regression.git
  #- git: https://gitee.com/canarias/rest_regression.git
    rev: 7cdfead22304fdbaa3a6436d90dfc0b07a4a13c6
    #branch: thread-option
    # tag: v2025.02
    target_directory: rest_regression

build:
  number: 0


requirements:
  build:
    - ${{ compiler('rust') }}
    - if: linux
      then: sysroot_linux-64 ==2.17
  # host:
  # run:

about:
  homepage: https://gitee.com/restgroup/rest_regression
  # summary: 'Rust-based Electronic-Structure Toolkit (REST), aiming at an efficient computational platform for state-of-the-art DFT and WFT methods.'
  # description: |
  #   Rust-based Electronic-Structure Toolkit (REST),
  #   aiming at an efficient computational platform for state-of-the-art DFT and WFT methods.
#   # Remember to specify the license variants for BSD, Apache, GPL, and LGPL.
#   # Use the SPDX identifier, e.g: GPL-2.0-only instead of GNU General Public License version 2.0
#   # See https://spdx.org/licenses/
# license: GPL-2.0-only
#   # The license_family, i.e. "BSD" if license is "BSD-3-Clause".
#   # Optional
#   license_family: MIT
#   # It is required to include a license file in the package,
#   # (even if the license doesn't require it) using the license_file entry.
#   # Please also note that some projects have multiple license files which all need to be added using a valid yaml list.
#   # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file
#   license_file: LICENSE.txt
#   # The doc_url and dev_url are optional.
#   doc_url: https://simplejson.readthedocs.io/
#   dev_url: https://github.com/simplejson/simplejson

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - jeanwsr
