c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
c_stdlib_version:
  -  2.17 # [linux and x86_64]
c_compiler:
  - gcc # [win]
cxx_compiler:
  - gxx # [win]
fortran_compiler:
  - gfortran # [win]
python:
  - 3.11
rust_compiler_version:
  - "1.94"
simple-dftd3:
  - 1.*
dftd4:
  - 4.*
hdf5:
  - 1.14.*
openmpi:
  - 4.*

