

package:
  name: "rest"
  version: "2026.1.0.3"

source:
  - git: git@gitee.com:restgroup/rest.git
  #- git: https://gitee.com/canarias/rest.git
    rev: 0a1ff34de509d18655ff4e710f44c7e4c478d399
    #branch: for-win
    target_directory: rest
  - git: git@gitee.com:restgroup/rest_tensors.git
  #- git: https://gitee.com/canarias/rest_tensors.git
    #tag: v2025.02
    rev: 1e2a2b8e1a9f8c80baf95f366743b1931bfd5aa9
    #branch: for-win
    target_directory: rest_tensors
  - git: git@gitee.com:restgroup/rest_libcint.git
  #- git: https://gitee.com/canarias/rest_libcint.git
    #tag: v2025.01
    rev: ba7ba116a06d3077faffc520fb1975e9e8587dcd
    #rev: 217c21a00a45cb41a45a4bafbd0f818f6d95dd04
    #branch: thread-safe
    target_directory: rest_libcint
  - git: git@gitee.com:restgroup/rest_regression.git
  #- git: https://gitee.com/canarias/rest_regression.git
    #tag: v2025.02
    rev: 7cdfead22304fdbaa3a6436d90dfc0b07a4a13c6
    #branch: win-invalid
    target_directory: rest_regression

build:
  number: 0
  files:
    exclude:
      - "**/__pycache__"
      - "**/test-files"
  script:
    env:
      REST_HOME: ${SRC_DIR}
      CONDA_BUILD_WINSDK: ${{ '${BUILD_PREFIX}/x86_64-w64-mingw32/sysroot' if target_platform == 'win-64' else '' }}

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
    - if: win
      then: m2w64-sysroot_win-64
    - if: not win
      then: ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - if: win
      then: rust-std-x86_64-pc-windows-gnu
    - if: win
      then: libclang
      else: libclang 21.*
    - hdf5
    - libcint
    - openblas * openmp*
    - python
    - libxc-c
    - if: not win
      then: openmpi 4.*
    - mokit
    - geometric
    - simple-dftd3
    - dftd4
    - if: osx
      then: llvm-openmp
  host:
    - hdf5
    - libcint
    - openblas * openmp*
    - python
    - libxc-c
    - if: not win
      then: openmpi 4.*
    - mokit
    - h5py
    - geometric
    - simple-dftd3
    - dftd4
    - if: osx
      then: llvm-openmp
  run:
    - hdf5
    - libcint
    - openblas * openmp*
    - python
    - libxc-c
    - if: not win
      then: openmpi 4.*
    - mokit
    - h5py
    - geometric
    - simple-dftd3
    - dftd4

tests:
  - if: not win
    then:
      script: run_tests.sh
      requirements:
        run:
          - restgroup::rest_regression
      files:
        source:
          - rest_regression

about:
  homepage: https://gitee.com/restgroup/rest
  summary: "Rust-based Electronic-Structure Toolkit (REST), aiming at an efficient computational platform for state-of-the-art DFT and WFT methods."
  description: |
    Rust-based Electronic-Structure Toolkit (REST), 
    aiming at an efficient computational platform for state-of-the-art DFT and WFT methods.
  license: GPL-2.0-only
#   # The license_family, i.e. "BSD" if license is "BSD-3-Clause".
#   # Optional
#   license_family: MIT
#   # It is required to include a license file in the package,
#   # (even if the license doesn't require it) using the license_file entry.
#   # Please also note that some projects have multiple license files which all need to be added using a valid yaml list.
#   # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file
#   license_file: LICENSE.txt
#   # The doc_url and dev_url are optional.
  documentation: https://rest-doc.readthedocs.io/en/index.html

extra:
  recipe-maintainers:
    - jeanwsr
